version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  veracode_sast_policy_scan:
    docker:
      - image: veracode/api-wrapper-java:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: List
          command: |
            zip -r upload.zip .
            ls -l | grep upload.zip
            java -jar /opt/veracode/api-wrapper.jar -vid $VID -vkey $VKEY -action uploadandscan -appname "NodeGoat-Demo" -createprofile true -version CircleCI-$CIRCLE_BUILD_NUM -filepath upload.zip

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - veracode_sast_policy_scan
